layout_spectrum: 0.9319149
typography_spectrum: 0.6702127
color:
  lightness: 0.1106383
  brandStrength: 0.5978723
  saturation: 0.9182237
  rhythmicContrast: 0.9617021
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
name: Lunarburn studio
